version: '3.8'

services:
  image-api:
    build: .
    container_name: image-api
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/home/root/MGVP/homework_pending
    environment:
      - NODE_ENV=production
    restart: always
