version: '3.8'

services:
  image-api:
    build: .
    container_name: image-api
    ports:
      - "5001:5001"
    volumes:
      - /home/root/MGVP:/home/root/MGVP  # ✅ Correct full mount
    environment:
      - NODE_ENV=production
    restart: always
